# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="random"
#ZSH_THEME="alanpeabody"
ZSH_THEME="crispy"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git command-not-found vi-mode jump)

source $ZSH/oh-my-zsh.sh

# User configuration

source $HOME/.shellrc-common

# make Esc not take ages to be detected (100ths of a second)
KEYTIMEOUT=5

# don't share history between terminals
# history can still be manually loaded into an individual session with: fc -RI
unsetopt append_history
unsetopt inc_append_history_time
unsetopt share_history
setopt inc_append_history

# use Ctrl-v binding in vim cmd mode to edit cmd in editor
zle -N edit-command-line
bindkey -M vicmd '^v' edit-command-line

# override copy/paste functions
function clipcopy() {
	~/.userenv/clipboard/pushclip.sh
}
function clippaste() {
	~/.userenv/clipboard/getcopybuffer.sh
}
function clippurge() {
	~/.userenv/clipboard/purge.sh
}

# Refresh stored X environment, or source it
X_ENV_FILE="$HOME/.user_env_x"
if [[ ! -z "$DISPLAY" ]] && [[ -z "$ZSHRC_SET_X_ENV" ]]; then
	env | grep -E '^(X|DISPLAY)' > "$X_ENV_FILE"
	chmod 600 "$X_ENV_FILE"
elif [[ -f "$X_ENV_FILE" ]] && [[ -z "$DISPLAY" ]]; then
	source "$X_ENV_FILE"
fi

# Start ssh-agent if not started, or source its env
SSH_ENV_FILE="$HOME/.ssh/agent_env"
function startsshagent() {
	echo 'Starting SSH agent.  "ssh-add" to enter password.'
	ssh-agent -s | grep -Ev '^echo' > "$SSH_ENV_FILE"
	chmod 600 "$SSH_ENV_FILE"
	source "$SSH_ENV_FILE"
}
if command -V ssh-agent &>/dev/null; then
	if [[ -f "$SSH_ENV_FILE" ]] && [[ -z "$SSH_AGENT_PID" ]]; then
		source "$SSH_ENV_FILE"
		if [[ -z "$SSH_AGENT_PID" ]]; then
			startsshagent
		else
			ps -p "$SSH_AGENT_PID" | grep "$USER" | grep -E '^ssh-agent' >/dev/null
			if [ $? -ne 0 ]; then
				startsshagent
			fi
		fi
	elif [[ -z "$SSH_AGENT_PID" ]]; then
		startsshagent
	fi
fi


# Don't set window title to directory
DISABLE_AUTO_TITLE=true

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
